apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-cluster-gitops
  namespace: argocd

spec:
  generators:
    - clusters: {}   # 👈 Automatically uses ALL clusters registered in ArgoCD

    - git:
        repoURL: https://github.com/Nonsocha/Gittops-cluster.git
        revision: HEAD
        directories:
          - path: service-*

  template:
    metadata:
      name: "{{name}}-{{path.basename}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/Nonsocha/Gittops-cluster.git
        targetRevision: HEAD
        path: "{{path}}"

      destination:
        server: "{{server}}"
        namespace: default

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
