apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-cluster-git-appset
  namespace: argocd

spec:
  generators:
    - matrix:
        generators:
          # Cluster definitions
          - list:
              elements:
                - cluster: cluster1
                  server: https://kubernetes.default.svc
                - cluster: cluster2
                  server: https://https://B2379F51DCD4EDE28535B15208E06A4C.gr7.us-east-1.eks.amazonaws.com   # replace this

          # Git structure
          - git:
              repoURL: https://github.com/Nonsocha/Gittops-cluster.git
              revision: HEAD
              directories:
                - path: service-*

  template:
    metadata:
      name: "{{path.basename}}-{{cluster}}"

    spec:
      project: default

      source:
        repoURL: https://github.com/Nonsocha/Gittops-cluster.git
        targetRevision: HEAD
        path: "{{path}}"

      destination:
        server: "{{server}}"
        namespace: default

      syncPolicy:
        automated:
          prune: true
          selfHeal: true