apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: nginx
        image: 707913648704.dkr.ecr.us-east-1.amazonaws.com/service-b:d9ca0100b68e1baf8c60aebb473446a82f2bb2f7
        ports:
        - containerPort: 80
